name: markdown2html
description: "markdown to html dart lib"
version: 0.0.1
homepage: https://github.com/mdddj/markdown2html

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_rust_bridge: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  meta: any

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
