// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/md.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:meta/meta.dart' as meta;

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MkCompileOptions dco_decode_box_autoadd_mk_compile_options(dynamic raw);

  @protected
  MkLineEnding dco_decode_box_autoadd_mk_line_ending(dynamic raw);

  @protected
  MkParseOptions dco_decode_box_autoadd_mk_parse_options(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MkCompileOptions dco_decode_mk_compile_options(dynamic raw);

  @protected
  MkConstructs dco_decode_mk_constructs(dynamic raw);

  @protected
  MkLineEnding dco_decode_mk_line_ending(dynamic raw);

  @protected
  MkParseOptions dco_decode_mk_parse_options(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MkCompileOptions? dco_decode_opt_box_autoadd_mk_compile_options(dynamic raw);

  @protected
  MkLineEnding? dco_decode_opt_box_autoadd_mk_line_ending(dynamic raw);

  @protected
  MkParseOptions? dco_decode_opt_box_autoadd_mk_parse_options(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MkCompileOptions sse_decode_box_autoadd_mk_compile_options(
      SseDeserializer deserializer);

  @protected
  MkLineEnding sse_decode_box_autoadd_mk_line_ending(
      SseDeserializer deserializer);

  @protected
  MkParseOptions sse_decode_box_autoadd_mk_parse_options(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MkCompileOptions sse_decode_mk_compile_options(SseDeserializer deserializer);

  @protected
  MkConstructs sse_decode_mk_constructs(SseDeserializer deserializer);

  @protected
  MkLineEnding sse_decode_mk_line_ending(SseDeserializer deserializer);

  @protected
  MkParseOptions sse_decode_mk_parse_options(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MkCompileOptions? sse_decode_opt_box_autoadd_mk_compile_options(
      SseDeserializer deserializer);

  @protected
  MkLineEnding? sse_decode_opt_box_autoadd_mk_line_ending(
      SseDeserializer deserializer);

  @protected
  MkParseOptions? sse_decode_opt_box_autoadd_mk_parse_options(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mk_compile_options(
      MkCompileOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mk_line_ending(
      MkLineEnding self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mk_parse_options(
      MkParseOptions self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_mk_compile_options(
      MkCompileOptions self, SseSerializer serializer);

  @protected
  void sse_encode_mk_constructs(MkConstructs self, SseSerializer serializer);

  @protected
  void sse_encode_mk_line_ending(MkLineEnding self, SseSerializer serializer);

  @protected
  void sse_encode_mk_parse_options(
      MkParseOptions self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mk_compile_options(
      MkCompileOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mk_line_ending(
      MkLineEnding? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mk_parse_options(
      MkParseOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
